const models    = require('../models');
const PDFDocument = require('pdfkit');

const TABLE_MAP = {
  cutting:               'Cutting',
  lamination:            'Lamination',
  printing:              'Printing',
  warehouse_to_dispatch: 'WarehouseToDispatch',
  dispatch_to_production:'DispatchToProduction',
  extruder:              'Extruder',
  raw_slitting:          'RawSlitting',
  pvc:                   'PVC',
  slitting:              'Slitting',
};

const SKIP = ['id','createdAt','updatedAt'];

function toCSV(records) {
  if (!records || records.length === 0) return 'No data\n';
  const keys = Object.keys(records[0]);
  const header = keys.join(',');
  const rows   = records.map(r =>
    keys.map(k => {
      const v = r[k] == null ? '' : String(r[k]);
      return v.includes(',') || v.includes('"') || v.includes('\n')
        ? `"${v.replace(/"/g,'""')}"` : v;
    }).join(',')
  );
  return [header, ...rows].join('\n');
}

function formatVal(v) {
  if (v == null) return '—';
  if (typeof v === 'number') return Number.isInteger(v) ? String(v) : v.toFixed(3).replace(/\.?0+$/, '');
  return String(v);
}

function drawPDFHeader(doc, company, title, ref) {
  // Header bar
  doc.rect(0, 0, doc.page.width, 55).fill('#1a3a5c');
  doc.fillColor('white').font('Helvetica-Bold').fontSize(18)
     .text(company, 30, 14, { continued: false });
  doc.font('Helvetica').fontSize(10)
     .text(title, doc.page.width - 200, 16, { width: 170, align: 'right' });
  doc.font('Helvetica-Bold').fontSize(12)
     .text(ref, doc.page.width - 200, 30, { width: 170, align: 'right' });
  doc.fillColor('#1a3a5c').rect(30, doc.page.height - 35, doc.page.width - 60, 0.5).fill();
  doc.font('Helvetica').fontSize(7).fillColor('#888')
     .text(`Generated by CI ERP  |  ${new Date().toISOString().slice(0,16).replace('T',' ')}`,
           30, doc.page.height - 28, { continued: true })
     .text('CONFIDENTIAL', { align: 'right' });
}

function drawTable(doc, headers, rows, startY, colWidths) {
  const BLUE = '#1a3a5c', LBLUE = '#e8f0fe';
  const ROW_H = 18, HEAD_H = 20;
  let y = startY;
  const totalW = colWidths.reduce((a,b) => a+b, 0);

  // Header row
  doc.rect(30, y, totalW, HEAD_H).fill(BLUE);
  let x = 30;
  doc.font('Helvetica-Bold').fontSize(7).fillColor('white');
  headers.forEach((h, i) => {
    doc.text(h, x + 3, y + 6, { width: colWidths[i] - 6, ellipsis: true });
    x += colWidths[i];
  });
  y += HEAD_H;

  // Data rows
  rows.forEach((row, ri) => {
    if (y + ROW_H > doc.page.height - 60) {
      doc.addPage();
      y = 70;
      // re-draw header
      doc.rect(30, y - HEAD_H - 2, totalW, HEAD_H).fill(BLUE);
      let hx = 30;
      doc.font('Helvetica-Bold').fontSize(7).fillColor('white');
      headers.forEach((h, i) => {
        doc.text(h, hx + 3, y - HEAD_H + 4, { width: colWidths[i] - 6, ellipsis: true });
        hx += colWidths[i];
      });
    }

    if (ri % 2 === 1) doc.rect(30, y, totalW, ROW_H).fill(LBLUE);
    let cx = 30;
    doc.font('Helvetica').fontSize(7).fillColor('#1a1a1a');
    row.forEach((cell, i) => {
      doc.text(formatVal(cell), cx + 3, y + 5, { width: colWidths[i] - 6, ellipsis: true });
      cx += colWidths[i];
    });
    // Row border
    doc.rect(30, y, totalW, ROW_H).stroke('#cccccc');
    y += ROW_H;
  });

  return y;
}

module.exports = {
  exportTableToCSV: async (req, res) => {
    try {
      const modelName = TABLE_MAP[req.params.tableName] || req.params.tableName;
      if (!models[modelName]) return res.status(404).json({ message: `Table '${modelName}' not found` });
      const records = await models[modelName].findAll({ raw: true });
      const csv = toCSV(records.map(r => {
        const clean = {};
        Object.keys(r).filter(k => !SKIP.includes(k)).forEach(k => clean[k] = r[k]);
        return clean;
      }));
      const fname = `${req.params.tableName}_${Date.now()}.csv`;
      res.setHeader('Content-Type', 'text/csv');
      res.setHeader('Content-Disposition', `attachment; filename="${fname}"`);
      res.send(csv);
    } catch (e) {
      console.error(e);
      res.status(500).json({ message: 'Export failed' });
    }
  },

  exportOrderToCSV: async (req, res) => {
    try {
      const { orderNumber } = req.params;
      const modelKeys = Object.keys(TABLE_MAP);
      const all = [];
      for (const key of modelKeys) {
        const name = TABLE_MAP[key];
        if (!models[name]) continue;
        const rows = await models[name].findAll({ where: { order_number: orderNumber }, raw: true });
        rows.forEach(r => {
          const clean = { source: key };
          Object.keys(r).filter(k => !SKIP.includes(k)).forEach(k => clean[k] = r[k]);
          all.push(clean);
        });
      }
      if (all.length === 0) return res.status(404).json({ message: 'No data for this order' });
      const csv = toCSV(all);
      res.setHeader('Content-Type', 'text/csv');
      res.setHeader('Content-Disposition', `attachment; filename="order_${orderNumber}.csv"`);
      res.send(csv);
    } catch (e) {
      console.error(e);
      res.status(500).json({ message: 'Export failed' });
    }
  },

  exportOrderToPDF: async (req, res) => {
    try {
      const { orderNumber } = req.params;
      // Try to load pdfkit; graceful fallback
      let PDFDoc;
      try { PDFDoc = require('pdfkit'); } catch(e) {
        return res.status(500).json({ message: 'pdfkit not installed. Run: npm install pdfkit' });
      }

      const doc = new PDFDoc({ size: 'A4', layout: 'landscape', margin: 30 });
      const chunks = [];
      doc.on('data', c => chunks.push(c));
      doc.on('end', () => {
        const pdf = Buffer.concat(chunks);
        res.setHeader('Content-Type', 'application/pdf');
        res.setHeader('Content-Disposition', `attachment; filename="order_${orderNumber}.pdf"`);
        res.send(pdf);
      });

      drawPDFHeader(doc, 'CI ERP', 'ORDER TRACKING REPORT', orderNumber);

      let y = 75;
      const PAGE_W = doc.page.width;

      for (const [key, modelName] of Object.entries(TABLE_MAP)) {
        if (!models[modelName]) continue;
        const rows = await models[modelName].findAll({ where: { order_number: orderNumber }, raw: true });
        if (!rows || rows.length === 0) continue;

        const cols = Object.keys(rows[0]).filter(k => !SKIP.includes(k));
        const colW = cols.length > 0 ? Math.floor((PAGE_W - 60) / cols.length) : 60;
        const colWidths = cols.map(() => colW);

        if (y + 40 > doc.page.height - 60) { doc.addPage(); y = 75; }

        doc.font('Helvetica-Bold').fontSize(11).fillColor('#1a3a5c')
           .text(`▸  ${key.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase())}`, 30, y);
        y += 18;

        const dataRows = rows.map(r => cols.map(c => r[c]));
        const headers  = cols.map(c => c.replace(/_/g,' ').replace(/\b\w/g, l => l.toUpperCase()));
        y = drawTable(doc, headers, dataRows, y, colWidths) + 10;
      }

      doc.end();
    } catch (e) {
      console.error(e);
      res.status(500).json({ message: 'PDF export failed' });
    }
  },
};
